---
title: "Figure Assignment"
author: "Yiming Wang"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
install.packages(c("knitr", "rmarkdown"))
```

```{r}
install.packages("tidyverse")

```

```{r}
install.packages("readxl")
```

```{r}
library(tidyverse)
```

```{r}
library(readxl)
```

```{r}
library(readxl)
```

```{r}
data_c<- read_excel("D:\\study_ucsd\\Winter_2025\\COGS_219\\figure_assignment(Yiming Wang)\\numerical_data_for_Figure_4.xlsx",sheet = 1)
```

```{r}
data_d<- read_excel("D:\\study_ucsd\\Winter_2025\\COGS_219\\figure_assignment(Yiming Wang)\\numerical_data_for_Figure_4.xlsx",sheet = 2)
```

```{r}
data_e<- read_excel("D:\\study_ucsd\\Winter_2025\\COGS_219\\figure_assignment(Yiming Wang)\\numerical_data_for_Figure_4.xlsx",sheet = 3)
```

```{r}
radical_distance_cols <- grep("Radical.distance", names(data_c), value = TRUE)

```

```{r}
radical_distance_cols
```

```{r}
if(length(radical_distance_cols) > 1){
  data_c <- data_c %>%
    select(-one_of(radical_distance_cols[-1]))
}

```

```{r}
names(data_c)[names(data_c) == radical_distance_cols[1]] <- "Radical_distance"
```

```{r}
data_c_long <- pivot_longer(
  data_c,
  cols = -Radical_distance,
  names_to = "Measurement",
  values_to = "g_r"
)
```

```{r}
data_c_filtered <- filter(data_c_long, Radical_distance >= 0 & Radical_distance <= 10)

```

```{r}
install.packages("scales")
```

```{r}
library(scales)
library(ggplot2)
```

```{r}
install.packages("dplyr")
```

```{r}
library(dplyr)
```

```{r}
print(data_c_filtered)
```

```{r}
peak_positions <- data_c_filtered %>%
  group_by(Measurement) %>%
  summarize(g_r = max(g_r), .groups = 'drop') %>%
  left_join(data_c_filtered, by = c("Measurement", "g_r" = "g_r")) %>%
  distinct(Measurement, Radical_distance, .keep_all = TRUE)
```

```{r}
peak_positions
```

```{r}
highest_peak <- peak_positions %>%
  filter(g_r == max(g_r)) %>%
  slice(1) 
print(highest_peak)
```

```{r}
data_c_filtered <- data_c_filtered %>%
  mutate(Measurement = factor(Measurement, levels = c("D_D2-Eu", "D_D2-H", "D_D2-N", "D_D2-O", "D_D2-C")))
```

```{r}
data_c_filtered
```

```{r}
data_c_filtered_finish <- data_c_filtered %>%
  mutate(Radical_distance = Radical_distance * 0.1)

highest_peak_finish <- highest_peak %>%
  mutate(Radical_distance = Radical_distance * 0.1)
```

```{r}
data_c_filtered_finish
```

```{r}
highest_peak_finish
```

```{r}
print(highest_peak_finish)
print(nrow(highest_peak_finish))
```

```{r}
ggplot() +
  geom_segment(data = highest_peak_finish, aes(x = Radical_distance, xend = Radical_distance, y = -1, yend = g_r), linetype = "dashed", color = "red") +
  
  geom_text(data = highest_peak_finish, aes(x = Radical_distance, y = g_r, label = sprintf("%.3f", Radical_distance)), vjust = 2.8, hjust = -0.2, color = "black")

```

```{r}
print(data_c_filtered_finish)
```


```{r}
# original plot in the paper
ggplot(data_c_filtered_finish, aes(x = Radical_distance, y = g_r, color = Measurement)) +
  geom_line() +
  
  scale_color_manual(values = c("D_D2-Eu" = "black", "D_D2-H" = "red", "D_D2-N" = "purple", "D_D2-C" = "green",  "D_D2-O" = "cyan"), breaks = c("D_D2-Eu", "D_D2-H", "D_D2-N", "D_D2-C", "D_D2-O")) +
  
  geom_segment(data = highest_peak_finish, aes(x = Radical_distance, xend = Radical_distance, y = -1, yend = g_r), linetype = "dashed", color = "red") +
  
  geom_text(data = highest_peak_finish, aes(x = Radical_distance, y = g_r, label = sprintf("%.3f", Radical_distance)), vjust = 34, hjust = -0.2, color = "black") +
  
  scale_x_continuous(limits = c(-0.1, 1),
                     breaks = seq(0, 1, by = 0.2),
                     labels = function(x) sprintf("%.1f", x)) +
  
  ylim(-1, 8.5) +
  
  labs(
    x = "Radial distance (nm)",
    y = "g(r)",
    color = "Measurement Type"
  ) +
  
  guides(color = guide_legend(title = NULL)) +
  
  theme_minimal() +
  theme(
    legend.position = c(0.95, 0.95),
    legend.justification = c("right", "top"),
    legend.box.just = "right"
  )

```

```{r}
# Improved plot 
ggplot(data_c_filtered_finish, aes(x = Radical_distance, y = g_r, color = Measurement)) +
  
  geom_line() +
  
  scale_color_manual(values = c("D_D2-Eu" = "black", "D_D2-H" = "red", "D_D2-N" = "purple", "D_D2-C" = "green","D_D2-O" = "cyan"), breaks = c("D_D2-Eu", "D_D2-H", "D_D2-N",  "D_D2-C","D_D2-O")) +
  
  geom_segment(data = highest_peak_finish, aes(x = -0.1, xend = Radical_distance, y = g_r, yend = g_r), linetype = "dashed", color = "red") +
  
  geom_segment(data = highest_peak_finish, aes(x = Radical_distance, xend = Radical_distance, y = -1, yend = g_r), linetype = "dashed", color = "red") +
  
  geom_label(data = highest_peak_finish, aes(x = Radical_distance, y = g_r, label = sprintf("%.5f", g_r)), vjust = 0, hjust = 4, color = "orange", fill = "white", fontface = "bold", size = 3.5, label.size = 0.5) +
  
  geom_label(data = highest_peak_finish, aes(x = Radical_distance * 0.1, y = g_r, label = sprintf("%.3f ", Radical_distance)), vjust = 21, hjust = -2.5, color = "blue", fill = "white", fontface = "bold", size = 3.5, label.size = 0.5) +
  
  scale_x_continuous(limits = c(-0.1,1), breaks = seq(0, 1, by = 0.2), labels = function(x) sprintf("%.1f", x)) +
  
  ylim(-1, 8.5) +
  
  labs(
    title = "Radial Distribution Function of Various Atom Pairs",
    x = "Radial Distance (nm)\nadsorbed deuterium atoms (D_D2)",
    y = "the framework atoms(Eu,H,N,C,O)\ng(r)",
    color = "Measurement Type"
  ) +
  
  theme_minimal() +
  theme(legend.position = "right",
        plot.title = element_text(hjust = 0.5) )

# RDF of various atom pairs between adsorbed deuterium atoms (D_D2) and the framework atoms

# Figure 4C shows that the first prominent peak for D2 adsorption occurs at 0.266 nm, corresponding to the D_D2-Eu atom pair, reaffirming the preferential adsorption of Eu clusters toward D2
```

```{r}
library(rmarkdown)

```

```{r}
# render("Figure_assignment.Rmd", output_format = "html_document")
# render("Figure_assignment.Rmd", output_format = "pdf_document")
```

